version: "3.7"

services:
  app:
    build:
      context: ./app
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_HOST: db
      TZ: "Asia/Tokyo"
    command: /bin/ash /go/src/app/scripts/wait_for_mysql.sh db test_user password air -d
  db:
    build:
      context: ./db/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/mysql/migrations:/docker-entrypoint-initdb.d
      - ./db/mysql/log:/var/log/mysql
      - ./db/mysql/conf.d:/etc/mysql/conf.d
  api:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./reference/openapi.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
